language: r
before_install:
    - R -e "install.packages('withr'); withr::with_envvar(RGL_USE_NULL = 'TRUE')"
addons:
  apt:
    packages:
    - libgdal-dev 
    - libftgl2 
    - libcgal-dev 
    - libglu1-mesa-dev 
    - libx11-dev 
    - libfreetype6-dev