language: r
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq freeglut3-dev xorg openbox
install:
    R -e "options(rgl.useNULL = TRUE)"
addons:
  apt:
    packages:
    - libgdal-dev 
    - libftgl2 
    - libcgal-dev 
    - libglu1-mesa-dev 
    - libx11-dev 
    - libfreetype6-dev